### ISSUE TITLE
All packages unauthorized but it passed in windows 10

### ISSUE THREAD

**Issue by barisx** [node-energy/node-energy-pre-commit-hooks#2]
`.pre-commit-config.yaml`:
```yaml
-   repo: https://github.com/node-energy/node-energy-pre-commit-hooks
    rev: v0.3.0
    hooks:
    -   id: liccheck-pipenv
```

```ini
# Authorized and unauthorized licenses in LOWER CASE
[Licenses]
authorized_licenses:


unauthorized_licenses:
        gpl v3
        bsd
        new bsd
        bsd license
        new bsd license
        simplified bsd
        apache
        apache 2.0
        apache software license
        gnu lgpl
        lgpl with exceptions or zpl
        isc license
        isc license (iscl)
        mit
        mit license
        python software foundation license
        zpl 2.1
        Apache Software
        GNU Library or Lesser General Public License (LGPL)
        Mozilla Public License 2.0 (MPL 2.0)
        Historical Permission Notice and Disclaimer (HPND)
        Python Software Foundation
        3-Clause BSD
        Apache-2.0
[Authorized Packages]
# Python software license (see http://zesty.ca/python/uuid.README.txt)
```
```bash
pre-commit run --all-files liccheck-pipenv
```

```
Run liccheck for projects using pipenv...................................Passed
```
